---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bar
  name: devops
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: bodeabbey/nana-devops-bc:latest
          ports:
            - containerPort: 8080
